import type { Currency } from '../types'

export const CURRENCIES: Currency[] = [
  // Major Fiat
  { code: 'USD', name: 'US Dollar', symbol: '$', type: 'fiat' },
  { code: 'EUR', name: 'Euro', symbol: '€', type: 'fiat' },
  { code: 'GBP', name: 'British Pound', symbol: '£', type: 'fiat' },
  { code: 'JPY', name: 'Japanese Yen', symbol: '¥', type: 'fiat' },
  { code: 'CHF', name: 'Swiss Franc', symbol: 'Fr', type: 'fiat' },
  { code: 'CAD', name: 'Canadian Dollar', symbol: 'C$', type: 'fiat' },
  { code: 'AUD', name: 'Australian Dollar', symbol: 'A$', type: 'fiat' },
  { code: 'CNY', name: 'Chinese Yuan', symbol: '¥', type: 'fiat' },
  { code: 'INR', name: 'Indian Rupee', symbol: '₹', type: 'fiat' },
  { code: 'SGD', name: 'Singapore Dollar', symbol: 'S$', type: 'fiat' },
  { code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK$', type: 'fiat' },
  { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr', type: 'fiat' },
  { code: 'SEK', name: 'Swedish Krona', symbol: 'kr', type: 'fiat' },
  { code: 'DKK', name: 'Danish Krone', symbol: 'kr', type: 'fiat' },
  { code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ$', type: 'fiat' },
  { code: 'MXN', name: 'Mexican Peso', symbol: 'Mex$', type: 'fiat' },
  { code: 'BRL', name: 'Brazilian Real', symbol: 'R$', type: 'fiat' },
  { code: 'KRW', name: 'South Korean Won', symbol: '₩', type: 'fiat' },
  { code: 'TWD', name: 'Taiwan Dollar', symbol: 'NT$', type: 'fiat' },
  { code: 'THB', name: 'Thai Baht', symbol: '฿', type: 'fiat' },
  { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM', type: 'fiat' },
  { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp', type: 'fiat' },
  { code: 'PHP', name: 'Philippine Peso', symbol: '₱', type: 'fiat' },
  { code: 'VND', name: 'Vietnamese Dong', symbol: '₫', type: 'fiat' },
  { code: 'ZAR', name: 'South African Rand', symbol: 'R', type: 'fiat' },
  { code: 'PLN', name: 'Polish Zloty', symbol: 'zł', type: 'fiat' },
  { code: 'CZK', name: 'Czech Koruna', symbol: 'Kč', type: 'fiat' },
  { code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft', type: 'fiat' },
  { code: 'TRY', name: 'Turkish Lira', symbol: '₺', type: 'fiat' },
  { code: 'RUB', name: 'Russian Ruble', symbol: '₽', type: 'fiat' },
  { code: 'BGN', name: 'Bulgarian Lev', symbol: 'лв', type: 'fiat' },
  { code: 'RON', name: 'Romanian Leu', symbol: 'lei', type: 'fiat' },
  { code: 'HRK', name: 'Croatian Kuna', symbol: 'kn', type: 'fiat' },
  { code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴', type: 'fiat' },
  { code: 'AED', name: 'UAE Dirham', symbol: 'د.إ', type: 'fiat' },
  { code: 'SAR', name: 'Saudi Riyal', symbol: '﷼', type: 'fiat' },
  { code: 'QAR', name: 'Qatari Riyal', symbol: '﷼', type: 'fiat' },
  { code: 'ILS', name: 'Israeli Shekel', symbol: '₪', type: 'fiat' },
  { code: 'EGP', name: 'Egyptian Pound', symbol: 'E£', type: 'fiat' },
  { code: 'NGN', name: 'Nigerian Naira', symbol: '₦', type: 'fiat' },
  { code: 'PKR', name: 'Pakistani Rupee', symbol: '₨', type: 'fiat' },
  { code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳', type: 'fiat' },
  { code: 'LKR', name: 'Sri Lankan Rupee', symbol: 'Rs', type: 'fiat' },
  { code: 'KES', name: 'Kenyan Shilling', symbol: 'KSh', type: 'fiat' },
  { code: 'GHS', name: 'Ghanaian Cedi', symbol: 'GH₵', type: 'fiat' },
  { code: 'ARS', name: 'Argentine Peso', symbol: 'AR$', type: 'fiat' },
  { code: 'CLP', name: 'Chilean Peso', symbol: 'CL$', type: 'fiat' },
  { code: 'COP', name: 'Colombian Peso', symbol: 'CO$', type: 'fiat' },
  { code: 'PEN', name: 'Peruvian Sol', symbol: 'S/', type: 'fiat' },
  { code: 'JMD', name: 'Jamaican Dollar', symbol: 'J$', type: 'fiat' },
  { code: 'CZK', name: 'Czech Koruna', symbol: 'Kč', type: 'fiat' },
  { code: 'IRR', name: 'Iranian Rial', symbol: '﷼', type: 'fiat' },
  { code: 'IQD', name: 'Iraqi Dinar', symbol: 'ع.د', type: 'fiat' },
  { code: 'AFN', name: 'Afghan Afghani', symbol: '؋', type: 'fiat' },
  { code: 'ALL', name: 'Albanian Lek', symbol: 'L', type: 'fiat' },
  { code: 'DZD', name: 'Algerian Dinar', symbol: 'د.ج', type: 'fiat' },
  { code: 'AOA', name: 'Angolan Kwanza', symbol: 'Kz', type: 'fiat' },
  { code: 'AMD', name: 'Armenian Dram', symbol: '֏', type: 'fiat' },
  { code: 'AZN', name: 'Azerbaijani Manat', symbol: '₼', type: 'fiat' },
  { code: 'BHD', name: 'Bahraini Dinar', symbol: '.د.ب', type: 'fiat' },
  { code: 'BBD', name: 'Barbadian Dollar', symbol: 'Bds$', type: 'fiat' },
  { code: 'BTN', name: 'Bhutanese Ngultrum', symbol: 'Nu.', type: 'fiat' },
  { code: 'BOB', name: 'Bolivian Boliviano', symbol: 'Bs.', type: 'fiat' },
  { code: 'BAM', name: 'Bosnia-Herzegovina Mark', symbol: 'KM', type: 'fiat' },
  { code: 'BWP', name: 'Botswanan Pula', symbol: 'P', type: 'fiat' },
  { code: 'BND', name: 'Brunei Dollar', symbol: 'B$', type: 'fiat' },
  { code: 'BIF', name: 'Burundian Franc', symbol: 'FBu', type: 'fiat' },
  { code: 'KHR', name: 'Cambodian Riel', symbol: '៛', type: 'fiat' },
  { code: 'CVE', name: 'Cape Verdean Escudo', symbol: 'Esc', type: 'fiat' },
  { code: 'XOF', name: 'CFA Franc (West)', symbol: 'CFA', type: 'fiat' },
  { code: 'XAF', name: 'CFA Franc (Central)', symbol: 'FCFA', type: 'fiat' },
  { code: 'CLF', name: 'Chilean Unit of Account', symbol: 'UF', type: 'fiat' },
  { code: 'KMF', name: 'Comorian Franc', symbol: 'CF', type: 'fiat' },
  { code: 'CRC', name: 'Costa Rican Colón', symbol: '₡', type: 'fiat' },
  { code: 'CUP', name: 'Cuban Peso', symbol: '₱', type: 'fiat' },
  { code: 'CDF', name: 'Congolese Franc', symbol: 'FC', type: 'fiat' },
  { code: 'DOP', name: 'Dominican Peso', symbol: 'RD$', type: 'fiat' },
  { code: 'DJF', name: 'Djiboutian Franc', symbol: 'Fdj', type: 'fiat' },
  { code: 'ERN', name: 'Eritrean Nakfa', symbol: 'Nfk', type: 'fiat' },
  { code: 'SZL', name: 'Eswatini Lilangeni', symbol: 'E', type: 'fiat' },
  { code: 'ETB', name: 'Ethiopian Birr', symbol: 'Br', type: 'fiat' },
  { code: 'FJD', name: 'Fijian Dollar', symbol: 'FJ$', type: 'fiat' },
  { code: 'GMD', name: 'Gambian Dalasi', symbol: 'D', type: 'fiat' },
  { code: 'GEL', name: 'Georgian Lari', symbol: '₾', type: 'fiat' },
  { code: 'GTQ', name: 'Guatemalan Quetzal', symbol: 'Q', type: 'fiat' },
  { code: 'GNF', name: 'Guinean Franc', symbol: 'FG', type: 'fiat' },
  { code: 'GYD', name: 'Guyanaese Dollar', symbol: 'GY$', type: 'fiat' },
  { code: 'HTG', name: 'Haitian Gourde', symbol: 'G', type: 'fiat' },
  { code: 'HNL', name: 'Honduran Lempira', symbol: 'L', type: 'fiat' },
  { code: 'ISK', name: 'Icelandic Króna', symbol: 'kr', type: 'fiat' },
  { code: 'JMD', name: 'Jamaican Dollar', symbol: 'J$', type: 'fiat' },
  { code: 'JOD', name: 'Jordanian Dinar', symbol: 'JD', type: 'fiat' },
  { code: 'KZT', name: 'Kazakhstani Tenge', symbol: '₸', type: 'fiat' },
  { code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'د.ك', type: 'fiat' },
  { code: 'KGS', name: 'Kyrgyzstani Som', symbol: 'сом', type: 'fiat' },
  { code: 'LAK', name: 'Laotian Kip', symbol: '₭', type: 'fiat' },
  { code: 'LBP', name: 'Lebanese Pound', symbol: 'L£', type: 'fiat' },
  { code: 'LSL', name: 'Lesotho Loti', symbol: 'M', type: 'fiat' },
  { code: 'LRD', name: 'Liberian Dollar', symbol: 'L$', type: 'fiat' },
  { code: 'LYD', name: 'Libyan Dinar', symbol: 'ل.د', type: 'fiat' },
  { code: 'MGA', name: 'Malagasy Ariary', symbol: 'Ar', type: 'fiat' },
  { code: 'MWK', name: 'Malawian Kwacha', symbol: 'MK', type: 'fiat' },
  { code: 'MVR', name: 'Maldivian Rufiyaa', symbol: 'Rf', type: 'fiat' },
  { code: 'MRO', name: 'Mauritanian Ouguiya', symbol: 'UM', type: 'fiat' },
  { code: 'MUR', name: 'Mauritian Rupee', symbol: '₨', type: 'fiat' },
  { code: 'MDL', name: 'Moldovan Leu', symbol: 'L', type: 'fiat' },
  { code: 'MNT', name: 'Mongolian Tugrik', symbol: '₮', type: 'fiat' },
  { code: 'MAD', name: 'Moroccan Dirham', symbol: 'MAD', type: 'fiat' },
  { code: 'MZN', name: 'Mozambican Metical', symbol: 'MT', type: 'fiat' },
  { code: 'MMK', name: 'Myanmar Kyat', symbol: 'K', type: 'fiat' },
  { code: 'NAD', name: 'Namibian Dollar', symbol: 'N$', type: 'fiat' },
  { code: 'NPR', name: 'Nepalese Rupee', symbol: '₨', type: 'fiat' },
  { code: 'NIO', name: 'Nicaraguan Córdoba', symbol: 'C$', type: 'fiat' },
  { code: 'OMR', name: 'Omani Rial', symbol: '﷼', type: 'fiat' },
  { code: 'PAB', name: 'Panamanian Balboa', symbol: 'B/.', type: 'fiat' },
  { code: 'PGK', name: 'Papua New Guinean Kina', symbol: 'K', type: 'fiat' },
  { code: 'PYG', name: 'Paraguayan Guarani', symbol: '₲', type: 'fiat' },
  { code: 'QAR', name: 'Qatari Riyal', symbol: '﷼', type: 'fiat' },
  { code: 'RWF', name: 'Rwandan Franc', symbol: 'RF', type: 'fiat' },
  { code: 'SOS', name: 'Somali Shilling', symbol: 'S', type: 'fiat' },
  { code: 'LKR', name: 'Sri Lankan Rupee', symbol: 'Rs', type: 'fiat' },
  { code: 'SDG', name: 'Sudanese Pound', symbol: 'SD', type: 'fiat' },
  { code: 'SRD', name: 'Surinamese Dollar', symbol: 'Sr$', type: 'fiat' },
  { code: 'SYP', name: 'Syrian Pound', symbol: '£S', type: 'fiat' },
  { code: 'TJS', name: 'Tajikistani Somoni', symbol: 'SM', type: 'fiat' },
  { code: 'TZS', name: 'Tanzanian Shilling', symbol: 'TSh', type: 'fiat' },
  { code: 'TMT', name: 'Turkmenistani Manat', symbol: 'T', type: 'fiat' },
  { code: 'UGX', name: 'Ugandan Shilling', symbol: 'USh', type: 'fiat' },
  { code: 'UYU', name: 'Uruguayan Peso', symbol: '$U', type: 'fiat' },
  { code: 'UZS', name: 'Uzbekistani Som', symbol: 'сўм', type: 'fiat' },
  { code: 'VUV', name: 'Vanuatu Vatu', symbol: 'VT', type: 'fiat' },
  { code: 'YER', name: 'Yemeni Rial', symbol: '﷼', type: 'fiat' },
  { code: 'ZMW', name: 'Zambian Kwacha', symbol: 'ZK', type: 'fiat' },
  { code: 'ZWL', name: 'Zimbabwean Dollar', symbol: 'Z$', type: 'fiat' },
  // Cryptocurrencies
  { code: 'BTC', name: 'Bitcoin', symbol: '₿', type: 'crypto' },
  { code: 'ETH', name: 'Ethereum', symbol: 'Ξ', type: 'crypto' },
  { code: 'USDT', name: 'Tether', symbol: '₮', type: 'crypto' },
  { code: 'USDC', name: 'USD Coin', symbol: '$', type: 'crypto' },
  { code: 'SOL', name: 'Solana', symbol: 'SOL', type: 'crypto' },
  { code: 'BNB', name: 'Binance Coin', symbol: 'BNB', type: 'crypto' },
  { code: 'DAI', name: 'Dai', symbol: 'DAI', type: 'crypto' },
  { code: 'XRP', name: 'XRP', symbol: 'XRP', type: 'crypto' },
  { code: 'ADA', name: 'Cardano', symbol: 'ADA', type: 'crypto' },
  { code: 'DOGE', name: 'Dogecoin', symbol: 'Ð', type: 'crypto' },
  { code: 'DOT', name: 'Polkadot', symbol: 'DOT', type: 'crypto' },
  { code: 'AVAX', name: 'Avalanche', symbol: 'AVAX', type: 'crypto' },
  { code: 'MATIC', name: 'Polygon', symbol: 'MATIC', type: 'crypto' },
  { code: 'LINK', name: 'Chainlink', symbol: 'LINK', type: 'crypto' },
  { code: 'UNI', name: 'Uniswap', symbol: 'UNI', type: 'crypto' },
  { code: 'ATOM', name: 'Cosmos', symbol: 'ATOM', type: 'crypto' },
  { code: 'LTC', name: 'Litecoin', symbol: 'Ł', type: 'crypto' },
  { code: 'BCH', name: 'Bitcoin Cash', symbol: 'BCH', type: 'crypto' },
  { code: 'XLM', name: 'Stellar', symbol: 'XLM', type: 'crypto' },
]

export function searchCurrencies(query: string): Currency[] {
  const q = query.toLowerCase()
  return CURRENCIES.filter(
    (c) =>
      c.code.toLowerCase().includes(q) ||
      c.name.toLowerCase().includes(q) ||
      c.symbol.toLowerCase().includes(q)
  )
}

export function getCurrency(code: string): Currency | undefined {
  return CURRENCIES.find((c) => c.code === code)
}
