// GET /api/currencies — static list of supported currencies
export const onRequestGet: PagesFunction = async () => {
  const currencies = [
    // Major Fiat
    { code: 'USD', name: 'US Dollar', symbol: '$', type: 'fiat' },
    { code: 'EUR', name: 'Euro', symbol: '€', type: 'fiat' },
    { code: 'GBP', name: 'British Pound', symbol: '£', type: 'fiat' },
    { code: 'JPY', name: 'Japanese Yen', symbol: '¥', type: 'fiat' },
    { code: 'CHF', name: 'Swiss Franc', symbol: 'Fr', type: 'fiat' },
    { code: 'CAD', name: 'Canadian Dollar', symbol: 'C$', type: 'fiat' },
    { code: 'AUD', name: 'Australian Dollar', symbol: 'A$', type: 'fiat' },
    { code: 'CNY', name: 'Chinese Yuan', symbol: '¥', type: 'fiat' },
    { code: 'INR', name: 'Indian Rupee', symbol: '₹', type: 'fiat' },
    { code: 'SGD', name: 'Singapore Dollar', symbol: 'S$', type: 'fiat' },
    { code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK$', type: 'fiat' },
    { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr', type: 'fiat' },
    { code: 'SEK', name: 'Swedish Krona', symbol: 'kr', type: 'fiat' },
    { code: 'DKK', name: 'Danish Krone', symbol: 'kr', type: 'fiat' },
    { code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ$', type: 'fiat' },
    { code: 'MXN', name: 'Mexican Peso', symbol: 'Mex$', type: 'fiat' },
    { code: 'BRL', name: 'Brazilian Real', symbol: 'R$', type: 'fiat' },
    { code: 'KRW', name: 'South Korean Won', symbol: '₩', type: 'fiat' },
    { code: 'TWD', name: 'Taiwan Dollar', symbol: 'NT$', type: 'fiat' },
    { code: 'THB', name: 'Thai Baht', symbol: '฿', type: 'fiat' },
    { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM', type: 'fiat' },
    { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp', type: 'fiat' },
    { code: 'PHP', name: 'Philippine Peso', symbol: '₱', type: 'fiat' },
    { code: 'VND', name: 'Vietnamese Dong', symbol: '₫', type: 'fiat' },
    { code: 'ZAR', name: 'South African Rand', symbol: 'R', type: 'fiat' },
    { code: 'PLN', name: 'Polish Zloty', symbol: 'zł', type: 'fiat' },
    { code: 'CZK', name: 'Czech Koruna', symbol: 'Kč', type: 'fiat' },
    { code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft', type: 'fiat' },
    { code: 'TRY', name: 'Turkish Lira', symbol: '₺', type: 'fiat' },
    { code: 'RUB', name: 'Russian Ruble', symbol: '₽', type: 'fiat' },
    { code: 'AED', name: 'UAE Dirham', symbol: 'د.إ', type: 'fiat' },
    { code: 'SAR', name: 'Saudi Riyal', symbol: '﷼', type: 'fiat' },
    { code: 'ILS', name: 'Israeli Shekel', symbol: '₪', type: 'fiat' },
    { code: 'EGP', name: 'Egyptian Pound', symbol: 'E£', type: 'fiat' },
    { code: 'NGN', name: 'Nigerian Naira', symbol: '₦', type: 'fiat' },
    { code: 'PKR', name: 'Pakistani Rupee', symbol: '₨', type: 'fiat' },
    { code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳', type: 'fiat' },
    { code: 'ARS', name: 'Argentine Peso', symbol: 'AR$', type: 'fiat' },
    { code: 'CLP', name: 'Chilean Peso', symbol: 'CL$', type: 'fiat' },
    { code: 'COP', name: 'Colombian Peso', symbol: 'CO$', type: 'fiat' },
    { code: 'PEN', name: 'Peruvian Sol', symbol: 'S/', type: 'fiat' },
    // Cryptocurrencies
    { code: 'BTC', name: 'Bitcoin', symbol: '₿', type: 'crypto' },
    { code: 'ETH', name: 'Ethereum', symbol: 'Ξ', type: 'crypto' },
    { code: 'USDT', name: 'Tether', symbol: '₮', type: 'crypto' },
    { code: 'USDC', name: 'USD Coin', symbol: '$', type: 'crypto' },
    { code: 'SOL', name: 'Solana', symbol: 'SOL', type: 'crypto' },
    { code: 'BNB', name: 'Binance Coin', symbol: 'BNB', type: 'crypto' },
    { code: 'XRP', name: 'XRP', symbol: 'XRP', type: 'crypto' },
    { code: 'ADA', name: 'Cardano', symbol: 'ADA', type: 'crypto' },
    { code: 'DOGE', name: 'Dogecoin', symbol: 'Ð', type: 'crypto' },
    { code: 'DOT', name: 'Polkadot', symbol: 'DOT', type: 'crypto' },
    { code: 'AVAX', name: 'Avalanche', symbol: 'AVAX', type: 'crypto' },
    { code: 'MATIC', name: 'Polygon', symbol: 'MATIC', type: 'crypto' },
    { code: 'LINK', name: 'Chainlink', symbol: 'LINK', type: 'crypto' },
    { code: 'UNI', name: 'Uniswap', symbol: 'UNI', type: 'crypto' },
    { code: 'LTC', name: 'Litecoin', symbol: 'Ł', type: 'crypto' },
  ]

  return Response.json({ currencies })
}
