export const DEFAULT_CATEGORIES = [
  // Income
  { name: 'Salary', type: 'income' as const, icon: '💼' },
  { name: 'Freelance', type: 'income' as const, icon: '💻' },
  { name: 'Investment Income', type: 'income' as const, icon: '📈' },
  { name: 'Rental Income', type: 'income' as const, icon: '🏠' },
  { name: 'Side Business', type: 'income' as const, icon: '🚀' },
  { name: 'Gifts Received', type: 'income' as const, icon: '🎁' },
  { name: 'Other Income', type: 'income' as const, icon: '💰' },

  // Expenses
  { name: 'Rent', type: 'expense' as const, icon: '🏠' },
  { name: 'Mortgage', type: 'expense' as const, icon: '🏡' },
  { name: 'Utilities', type: 'expense' as const, icon: '💡' },
  { name: 'Internet', type: 'expense' as const, icon: '🌐' },
  { name: 'Home Insurance', type: 'expense' as const, icon: '🛡️' },
  { name: 'Home Maintenance', type: 'expense' as const, icon: '🔧' },
  { name: 'Car Payment', type: 'expense' as const, icon: '🚗' },
  { name: 'Gas', type: 'expense' as const, icon: '⛽' },
  { name: 'Car Insurance', type: 'expense' as const, icon: '🛡️' },
  { name: 'Public Transit', type: 'expense' as const, icon: '🚇' },
  { name: 'Groceries', type: 'expense' as const, icon: '🛒' },
  { name: 'Dining Out', type: 'expense' as const, icon: '🍽️' },
  { name: 'Coffee', type: 'expense' as const, icon: '☕' },
  { name: 'Health Insurance', type: 'expense' as const, icon: '🏥' },
  { name: 'Doctor', type: 'expense' as const, icon: '👨‍⚕️' },
  { name: 'Gym', type: 'expense' as const, icon: '🏋️' },
  { name: 'Clothing', type: 'expense' as const, icon: '👔' },
  { name: 'Entertainment', type: 'expense' as const, icon: '🎬' },
  { name: 'Subscriptions', type: 'expense' as const, icon: '📱' },
  { name: 'Travel', type: 'expense' as const, icon: '✈️' },
  { name: 'Taxes', type: 'expense' as const, icon: '🏛️' },
  { name: 'Miscellaneous', type: 'expense' as const, icon: '📦' },
]
